.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH flightlog-validate 1 2026-09-28 "flightlog 0.2.1" "flightlog manual"
.SH NAME
flightlog\-validate \- Check a bundle against the format; exits 1 listing every problem
.SH SYNOPSIS
\fBflightlog validate\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Check a bundle against the format; exits 1 listing every problem
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
The .flightlog.zip
.SH SEE ALSO
.BR flightlog (1)
