.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH flightlog-skills-show 1 2026-09-28 "flightlog 0.2.2" "flightlog manual"
.SH NAME
flightlog\-skills\-show \- Print a skill\*(Aqs SKILL.md
.SH SYNOPSIS
\fBflightlog skills show\fR [\fB\-h\fR|\fB\-\-help\fR] [\fINAME\fR]
.SH DESCRIPTION
Print a skill\*(Aqs SKILL.md
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fINAME\fR] [default: flightlog\-export]
flightlog\-export or flightlog\-import
.SH SEE ALSO
.BR flightlog (1)
