.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH flightlog-inspect 1 2026-09-28 "flightlog 0.2.1" "flightlog manual"
.SH NAME
flightlog\-inspect \- Show a bundle\*(Aqs summary, source, stats and redaction report
.SH SYNOPSIS
\fBflightlog inspect\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Show a bundle\*(Aqs summary, source, stats and redaction report
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
The .flightlog.zip
.SH SEE ALSO
.BR flightlog (1)
